TwilioChat.Web/Controllers/ChatController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using Twilio;
using Twilio.Rest.Chat.V1.Service;
using TwilioChat.Web.Models;
using Twilio.Rest.Chat.V1.Service.Channel;
using static Twilio.Rest.Chat.V1.Service.ChannelResource;
using Twilio.Rest.Chat.V1.Service.User;
using System.Collections.Generic;

namespace TwilioChat.Web.Controllers
{
    public class ChatController : Controller
    {
        private readonly TwilioAccount _twilioAccount;
        private readonly ILogger _logger;

        public ChatController(IOptions<TwilioAccount> twilioAccount, ILoggerFactory logger)
        {
            _logger = logger.CreateLogger("TwilioChat");
            _twilioAccount = twilioAccount.Value ?? throw new ArgumentException(nameof(twilioAccount));
            TwilioClient.Init(_twilioAccount.ApiKey, _twilioAccount.ApiSecret, _twilioAccount.AccountSid);
        }

        public IActionResult Index(string userName, string channelSid)
        {
            //string userName = string.Empty;
            //Request.Cookies.TryGetValue("UserName", out userName);

            // Get list all users.
            var users = UserResource.Read(pathServiceSid: _twilioAccount.ChatServiceSid, limit: 20);

            // Get a user.
            UserResource chatUser = null;
            foreach (var user in users)
            {
                if (user.Identity == userName)
                {
                    chatUser = user;
                    break;
                }
            }

            // Create a user.
            if (chatUser == null)
            {
                chatUser = UserResource.Create(
                    identity: userName,
                    pathServiceSid: _twilioAccount.ChatServiceSid
                );
            }

            // Get the user's channels.
            var channels = new List<ChannelModel>();

            var userChannels = UserChannelResource.Read(
                pathServiceSid: _twilioAccount.ChatServiceSid,
                pathUserSid: chatUser.Sid
            );

            foreach (var record in userChannels)
            {
                // Find the member in the channels.
                var channelMembers = MemberResource.Read(
                    pathServiceSid: _twilioAccount.ChatServiceSid,
                    pathChannelSid: record.ChannelSid
                );

                channels.Add(new ChannelModel()
                {
                    ChannelSid = record.ChannelSid,
                    Member = channelMembers.Where(x => x.Identity != chatUser.Identity).Select(x => x.Identity).First(),
                    UnreadMessagesCount = record.UnreadMessagesCount
                });
            }

            // Set default channel.
            if (string.IsNullOrEmpty(channelSid) || !channels.Any(x => x.ChannelSid == channelSid))
            {
                channelSid = channels.Select(x => x.ChannelSid).FirstOrDefault();
            }

            // Get last messages.
            var messages = new List<MessageResource>();

            try
            {
                messages = MessageResource.Read(
                   pathServiceSid: _twilioAccount.ChatServiceSid,
                   pathChannelSid: channelSid,
                   limit: 20
               ).ToList();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
            }

            var model = new ChatModel()
            {
                UserName = userName,
                ChannelSid = channelSid,
                Users = users.Where(x => x.Sid != chatUser.Sid).ToList(),
                Channels = channels,
                Messages = messages

            };

            // Response.Cookies.Append("ChannelSid", channelSid);
            return View(model);
        }

        // Add a new channel.
        [HttpPost]
        public void Create(string userName, string member)
        {
            // Create a channel.
            var channel = ChannelResource.Create(
                pathServiceSid: _twilioAccount.ChatServiceSid,
                uniqueName: $"{userName}_{member}",
                type: ChannelTypeEnum.Private
            );

            // Add members.
            var member1 = MemberResource.Create(
                identity: userName,
                pathServiceSid: _twilioAccount.ChatServiceSid,
                pathChannelSid: channel.Sid
            );
            var member2 = MemberResource.Create(
                identity: member,
                pathServiceSid: _twilioAccount.ChatServiceSid,
                pathChannelSid: channel.Sid
            );
        }

        // Delete the channel.
        [HttpGet]
        public IActionResult Delete(string userName, string channelSid)
        {
            ChannelResource.Delete(
                pathServiceSid: _twilioAccount.ChatServiceSid,
                pathSid: channelSid
            );

            return RedirectToAction("Index", new { userName, channelSid });
        }
    }
}

TwilioChat.Web/Views/Chat/Index.cshtml
@using TwilioChat.Web.Models
@model TwilioChat.Web.Models.ChatModel
@{
    ViewData["Title"] = "Twilio Chat";
    ViewData["User"] = Model.UserName;
}

@section Styles{
    <link rel="shortcut icon" href="//www.twilio.com/marketing/bundles/marketing/img/favicons/favicon.ico">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href="~/css/chat.css" rel="stylesheet" />
}

@Html.Hidden("username", Model.UserName)
@Html.Hidden("channelsid", Model.ChannelSid)

<div class="messaging">
    <div class="inbox_msg">
        <div class="inbox_people">
            <div class="inbox_chat">
                <div class="chat_list current_user">
                    <div class="chat_people">
                        <div class="chat_img"> <img src="~/images/user-profile.png"> </div>
                        <div class="chat_ib">
                            <h5>@Model.UserName</h5>
                            <button  data-toggle="modal" data-target="#addChannelModal">+Channel</button>
                        </div>
                    </div>
                </div>
                @foreach (var channel in Model.Channels)
                {
                    <div class="chat_list @(channel.ChannelSid == Model.ChannelSid ? "active_chat" : "")">
                        <div class="chat_people">                            
                                <div class="chat_img"> <img src="~/images/user-profile.png"> </div>
                                <div class="chat_ib">
                                    <a asp-controller="Chat" asp-action="Index" asp-route-username="@Model.UserName" asp-route-channelsid="@channel.ChannelSid">
                                        <h5>@channel.Member <span class="chat_date">@channel.UnreadMessagesCount</span></h5>
                                    </a>
                                    @*<a asp-controller="Chat" asp-action="Delete" asp-route-username="@Model.UserName" asp-route-channelsid="@channel.ChannelSid">
                                        <i id="deleteChannel" class="fa fa-trash"></i>
                                    </a>*@
                                </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="messages">
            <div id="msg_history" class="msg_history">
                @foreach (var message in Model.Messages)
                {
                    @if (message.From != Model.UserName)
                    {
                        <div class="incoming_msg">
                            <span class="time_date"> @message.DateCreated</span>
                            <p>@message.Body</p>
                        </div>
                    }
                    else
                    {
                        <div class="outgoing_msg">
                            <span class="time_date"> @message.DateCreated</span>
                            <p>@message.Body</p>
                        </div>
                    }
                }
            </div>
            <div class="type_msg">
                <div class="input_msg_write">
                    <input id="chat-input" type="text" class="write_msg" placeholder="Type a message" />
                    <button id="chat_send_btn" class="msg_send_btn" type="button"><i class="fa fa-paper-plane-o" aria-hidden="true"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="addChannelModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Select User</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="overflow-auto">
                    <table id="usersTable" class="table table-bordered table-hover">
                        <tbody>
                            @foreach (var user in Model.Users)
                            {
                                <tr>
                                    <td>@user.Identity</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script src="https://media.twiliocdn.com/sdk/js/common/v0.1/twilio-common.min.js"></script>
    <script src="https://media.twiliocdn.com/sdk/js/chat/v3.0/twilio-chat.min.js"></script>
    <script src="~/js/chat.js"></script>
}